# Site settings
title: dondenton.name
description: > # this means to ignore newlines until "baseurl:"
  A little story about GoDaddy and April
twitter_username: donnydenton
github_username:  happycollision

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dondenton.name" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart']

permalink: pretty

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
